name: Build and Publish Java Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Setup hardware emulator using QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 4: Log in to Docker Hub using secrets for credentials
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Extract metadata (tags) for the Docker image
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: henrylamb/data-capstone:1.0.0, henrylamb/data-capstone:latest

      # Step 6: Build and push the Docker image with SBOM and provenance
      - name: Build and push Docker image with SBOM and provenance
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          sbom: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64, linux/arm64
